#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import re
import os
import sys

# ---------- 1. ANLAMLI İSİM EŞLEMELERİ (Fonksiyonlar ve Değişkenler) ----------
REPLACE_MAP = {
    # Ana fonksiyonlar
    'QYLAXKZHDEYYRWUFWLBWHWAXAPHSSENRTANSILNXJEDOSMPQBANCCCDQOGCFAOFZTNBFWXFXIPLCAXVKQMQT': 'check_windows',
    'BEVBSMZECFMIVAPLFRNVDRYDGWOAYLPDMLVYGJWENOFCNXXVRWFEJGMBHFSVTHWZBPNYESVYOHQAMFDSEUFHX': 'collect_system_info',
    'SOIUJPRNQWAUHNOMYSJFYCAJOUCDTCAINNKAFBBHXBFZVBTVJQH': 'collect_discord_tokens',
    'BXVPDKBJEQMBPMSQYOQCIDFVPSODHBRHYBWBQFCTIZBSOZVTPQBMIUNRKOBGUPPURQKXTTNSUMIWLKCSWADDSRKANSPNPFWIRW': 'collect_browser_data',
    'DEKOTYCSNLZSPXVUKKMKLMVISYWWDYQYJFDODPGUBYYMPTAGUJDEBUCWYUMSBCZXZTUMYLUC': 'collect_roblox_cookies',
    'IWIQAIRTPCHYJNDLWLHTCVXCVTGYTJAYSMNACNEKJVSQOKQLIZZXQHBWUN': 'take_screenshot',
    'AVKNTIBOGFSKOOKMIBXXLNAEBMHZDRWGOFTAGSUNAKKSFELESEWKHJCUNPPMXHVPHHPPEBOJKHKE': 'collect_wallets_apps',
    'BGLFBEINUMMQWTNVMPRLTVJDDBDKUHEPTNPZFPKORWVLKUCHOJBTMEOAZQCWAEDIQHNVIZWCFTMHMNEMBDHGLPDFFGUBKKDI': 'collect_interesting_files',
    'YTUDOCEYEOXQQCKOIVQGMXKMFVEEUJBADDLKPWLYYWKQKBRPPMJMDKTONJHWSFKAHIGLLHLLNSKPZWQZKLVEHOZJ': 'capture_camera',
    'QZTGDWFIDRTJCGSETKESBEFADOWYEZXDUWCEPSPYHIXDUAXNQZSVBXWCKQARDSZNDJRESRCFPPSPSTQY': 'discord_injection',
    'VUSQRGIMUDRPCZKYROOMTACCFETMQTWAMZAGWKXRDDDNMJCCSCHHFHWJDTYEV': 'set_console_title',
    'CAVTWVPTKUGAACHBKCXXOWOPIQGBDWKSITICJAUFNCVBXSDYSHXFUWQIARKYAWND': 'clear_screen',
    'ZKSDHAYXMUBDNCRTUDAEXBYQXHOESECRKTYTMPKCRSEIULCUEHSNTITMDDPPFLHTQDGSKDPDQJHGNXOMYPYCYWBYKMQWJMA': 'aes_gcm_decrypt',
    'HWKNXIIZFCFHSEQPYTDSWZALQMRQQIHMLNHZGOJJZUMIKMLYPMAERMYWAQKTPFVMTHKCXQSGBNZSJTMSPODW': 'empty_thread_1',
    'AMDPKPGVPRQQHNPVPAUTCZIDLXNZDTFTVYMPWRCLKMVJUNSNNUHDOXKIABSGKCYKMJWZMCJKCIASJNBUGIWZJTUBEVQ': 'empty_thread_2',
    'YATNIFGGKGMHKMJAQWQEEDGWSFBJSEXBSQSPQUJHLROMPDLIXPOQXRGLIGQUYCRAPLWWHINYDKSNKWJLLEROWQ': 'empty_thread_3',
    'ACCSHEUCIAISDEUNQLNETXVHWDDFHLZRHEXFJBONZSNXYQMGWMXXFFRNFMVUYCXDLETMLWWJPPWJZZJDP': 'empty_thread_4',
    'QKDCVEQYRABCGIZGQDORTBMBGSUJLYIWROEPMMYUXFZGWPUDEIDPJABMROOWBMZUXBDQBPSWGSXHYPIIYSRCPSETUWUBEJQI': 'empty_thread_5',
    'LZMZXKHPRNYJRMHMSWBHPJPMOAIZAJOHFIDXVCQDLKFCHUZNYTFWDQETYJSJCHPDNFZFYLRHJU': 'empty_thread_6',
    'RNCFVMFPBJKRTICRAPBNNAAHKSAYJMKIKAQQVTQDVMHMPEWAINUZNBOF': 'empty_thread_7',
    'LPRSXWZRWUQQSAQWQZWLUYVQODVAEXVIHTOPHOSSXGJHFCYKRCAFUQU': 'empty_thread_8',
    'OJHYYYORUWUUFROBNFXDYMRIGJMDFFBSTHZYVNDABOYVSBRERQSDORSIYQJXGPUHLNWYDZGARSJOOT': 'empty_thread_9',
    'YUFNBIGIQLPDBQYXOMKJAPHSBFJCLODGQIKPGUWBOTJHHXVLRSCXOUHAJMDZWZCAONYFZAIHRLGAQQIAQL': 'empty_thread_10',
    'GIEHHIURPJORNYCPGCNDMUZAKLKRNTYJOOLGHQFFSRIQIOAWZRNIOCOCILJYMRFWCITQGKUMZWBCA': 'empty_thread_11',
    'HDJSVVIIGWCXAEHZFYTAQJFHYMWXQNMHWXPVGMLOFQCDKYRYAUZEFFASFNNVSDIWOFRRFYMLMXMBCG': 'empty_thread_12',

    # Ana değişkenler (sistem bilgisi)
    'TMFFAKPLSOYENTTLWIGJELFFHNQFRDFBOGUSFPKOSYPNMNGKNAQQMHMSSEDZLUUBLWXZGCDISISIXTYXGZGHENVIP': 'hostname',
    'EBSOKFTBXTAQJEYUJGHDFTTGPWBYLIVVIHTZESHHFAYQTXPOITNUQDTH': 'username',
    'DUJXYEYUFXDXAIACZUIUVIOXDAZWXSUJGTEHLVTACZMNRWWHXBIAQQNDUBUQGCWYUHBD': 'display_name',
    'PMWKXIQKDKKMYXVZAEPWOWGVJCBZECEKWDBDHWADKLRFQWNIDZCAIIEFAKCCVWPUXJAITZUVGCZDCSIUWONKVWWZGJIMNCYEABVB': 'public_ip',
    'CPSVWAQCBXXMYXAWIKBPQQOHPQRGGLZAQXNRTGMBSIQTMTEVGONMMSEAKQRWKJOMYYUWPNQODISVFIYCVEU': 'local_ip',
    'IZUGSHCXOJZZLQVEOEEBFHHANHDQRIFXQSXOWYNMEJTSGVWQCZDUSXQCXHWFT': 'country',
    'CXSAASMLRGOAFMYCHTRSNLIRYITHKXDHJKSYZXGHWCTOPSDGBTIBIGGGCIXZBJURUWQHFNZR': 'country_code',
    'RVRERXKINVAFYKUJPXTWQUFYYLWUONOURZTKCUARFTQCVABHJYJUTUHUIAOVYSHENRUVMWWAXHJHGG': 'region_name',
    'MOINJPBYSESFXMBWCYWOZWPNSIFJELTQXEBXMBZTUZIQKEKRPXCRTVFZJWZNCCJZCFWNDBQKEDFPJN': 'region',
    'KXAJXLUDDGRNHDCLFRXSKQFSIOGVUBVTOOXIOELRPHKIONSIBXPQAOQTAODLNRTZCFYBW': 'zip_code',
    'JRIIUVHTGLYHPJHQFXZSRXAMFGWEUVCRCACROHESRSQYRQOCLVQOWSHGZDFBT': 'city',
    'XYCFVAXJPWWSBFDXICRTYNUYPBKGACYBLADFILIRTWUJFAOTMIWTATHLYJIFMV': 'latitude',
    'ZAWKUJRRTOMIVMUIKHPGYOIKQAZPJOFYZWOYNTFIETFRHBOLLSYEJAVHGKEXBZACBFOBOXJLBWVWTOGSDQMUKTJJTUPUAXSGN': 'longitude',
    'GDVCQDRRIGKATZMJCWARKBBVLFTXLCOCTVUPPERRONJFVNUOEDNTAPXXWTPRO': 'timezone',
    'LBVDKDQXXGKRCLONLQTCWTKKBACHOLYNOOPZOIFHLJNWMXNMEKDVCGCVGYNNXZLBFGFVDQYDWJEABFKCKRTSKJW': 'isp',
    'LCCWNIKERMLDGAOHFLXXARMGXNPBTXYCZQQWRUYPOMSMAWXNLWTDWNAYGLOIQHUSLZBEMAAYFWHXZKISZKAVQMKCRLEANJHBG': 'org',
    'MXKHXRKZJEGSSABKFVKPNKTIILCVEERKCYBADIASFORHJQAOYYTLVEOSYIGPMWEMZSRGZVPLUKDBAFYXSXYIEOLIB': 'asn',

    # Sabitler / Şifreli veriler
    'FCHHXDLKJYJTWNPNKEHBNFHTJXZAIMBHPJQEDPBAMRSCOBIQTKKHBLLADXUTUSFZYKPAWPIYWWFGCNRZUBGTKFCEBEUWZUDFHJ': 'encrypted_webhook',
    'PHUCDEJMSFKHAKZEMXMGUPABKWGPMSGRLBJXCGBUTNWJDXROSKZKKWZF': 'webhook_key',
    'PGGZYKQXPAOMJNOEXMLQEHZGMFEDQKUMYQJTWSEZUCMDAILRIRARFFLNQWAPGOKGUCUXUODBNJOTXZNUIDZXBWMQYFCGTTP': 'ip_api_domain',
    'DXRWFYKCSMOZBKUBBKSRFUIDRXHSDHPADWSHHZWXKZMCQVRLICLMTNTWFCHZ': 'embed_color',
    'MCJBUVBUELHELQLVYOSQBWFYSRNHRPRLSFNHQIRIWQBVATNPOZDYUXVEVASGILNTLYXBVNZOWMGNZXS': 'webhook_username',
    'NVVRWSXRPVFFRLYPKJTEQKALQBDEBWBPCNRSHFYLCJMLZXFMRSDWWHIGFXRWCKUNFGQGCGGSFWQYCWODYHESVMTSTMSCSCBCHUHM': 'avatar_url',
    'MYZGNFZGVMVSHEOXYVLDSFRJBIFUBATQPKNEUHLVBLHTRHXERJGZZTQUODM': 'footer_text',
    'MWNIQFCVULCQMCBJHXAIONOBQLJPLRAIHUOMDLNDGPQMCFQIZO': 'footer_dict',
    'YNTQKNDJUGWPDLZFVLBSSGBSEEHHCXBIXSIREKCXYRSSAKSQMJFMK': 'webhook_content',

    # Klasör yolları
    'UHIHVDUIXNIPEEGWKBOWYTGOADQBFJYXKRBHSUMJIVOKIUCHFFLOWJMOQAXIJQOYLOQBDQTJYFOVEYLURYHNBFVZGCQVGT': 'windir',
    'DQZBRHOZNRRLGFSSPWLCXYRIOQWTPJBUJRCMHHEFPHGHVRGJACQXFWNEMMEJUMRJMXFBMHIUFJVLTEB': 'user_profile',
    'OFRKFMOQXPHBNFXHYOXKUKMYTMCUYKJTVQQRJHUAURRDAVVQZYYLWDGTYTDTYZZTITR': 'local_app_data',
    'ANYKMJJAGVKLCQKOPQHCSHTNPNMDGLNNIHCLYGXTIGAZXPKYYOWRQSCUUEWNAJUQKGFPVXAPYPQVJPEPVZYOFWYNLIINWICVJ': 'app_data',
    'KLOPENBSGHDQZYTDJQPAWYYVBJWEIJEFPNZQSZXRJPILYRKDTDKHRHBZDWYWTCETZRYNBSZCXAHWRZOUWCT': 'program_files_x86',

    # Discord token toplama içindeki yardımcılar
    'DMDWUOLBEWLMNQGNOAOTAHXABPQEMXYSWROEGJLFVNZTGYVORLQEICIJXTDWPGUPLHIGYPJLAJJWJZMJJAOEPZBLIYGOCDJCTQA': 'get_decryption_key',
    'QMAIWNMHOBNBKNWTRRDGODBEYYJKRWNSQBDSORSCXXDRJZONKTLNZWNOEGGJWZSZOKGDTUATSYQC': 'decrypt_discord_token',
    'PLISFAKRZRNVXFIITAFRYPVUQZFIXOUPNLKYUZXUSZIHCYPLHBFDNO': 'is_token_valid',
    'CQJDSKUZMOGCMYLYGRUVFXJFUFVPXSDQWFIMJEMQVRTTXWXXSRAFRELCOAZNJPDEPXUWEYRMUPODRSDPIDGEYZONWFCZIQQEB': 'find_all_discord_tokens',

    # Browser data içindeki yardımcılar (global'ler de dahil)
    'FLVJNMNJIDRUONBHIEBSCKVHNBRZJIXWDMDCANLBPVMHSYYZGSHVCTAJBBSFMDVGLCLXNRLNUGCIRYZQIVHOTPJ': 'extract_passwords',
    'PMCULLFEWFYRMICGARJJSPLWQYKXQSFQXSNWCMCKQJXPXLUJREBCMVDAOXTWMEXIAGMMIHVMOJFNAMUOUWHKSLTSACT': 'extract_cookies',
    'CYLBNPKYFMJAEWADGLMQGTZREOQMDQEVZJJSDIWYYUSZXNDKCXAJRGHWCXQAMEMWYNIEJZEYUGLRSDWFHOZLBOKSF': 'extract_history',
    'JREKYVLPIHNXUJXKEILRSNOSUEDQRVRLBOINJBZDXMSHVVQXLWXVTXAXKUBQ': 'extract_downloads',
    'IHWHAXTWMEWKDXMQVZYFZUZFQCYMLFRLAMYNIVFFMSZNDJDIAJLKUZAYC': 'extract_credit_cards',
    'TOHZGGUOCTTSTEZZCTIADEHHOBFXDIHVGIYQHMCTABSTEGAKOCJYVGQVPWV': 'extract_extensions',

    # Roblox cookie toplama içindeki yardımcılar
    'HGTHZEFWXUWMFHBFUXTXRZGEELMPMZHFKXKMYHJMIYCEHOIHYWEPYYFECZICGNXORNYVRMPEUDXKPHEFRKZFMVG': 'extract_roblox_cookie_from_browser',

    # Wallets/Apps içindeki yardımcılar
    'EIZQGNNQGDTTJMSGHKJEUXTJOFRQPRXHGJCONLMYYUQRZZBBTSXBLAA': 'wallet_app_paths',
    'BEWQQHTCHMVHOJTSOALDDSVOSHUQOPJLFNSIDYXTSOCNBWVQDISBKJTFFIVLKJKZBZKMBAE': 'target_categories',

    # Diğer rastgele değişkenler (Discord token işlemleri)
    'WNJKQVFFVBGBHLBZOZZCWXSGOEBRFKSGJXNGJAOAZLRHHOPVPMBBDFEINWHCTPYIRAPBHPIAPFGNMKXLXTRLLLDOKHVNMUOOKTK': 'discord_api_me',
    'MWPNZPKORFQEKZFLAKCGIRJFZHXRKFLRFXHYCMWXQTSMNPWFKLCTIOKJQC': 'token_regex',
    'NYESPHQDBXLBBOSWKITWJWPZUSGLWRXCTBZDFUGNMCESHASGNIMDSPHNQCAUYAYESHJJXKEAUN': 'encrypted_token_regex',
    'CDXEJZEHGGGAEAZERUUXILVKDHRFJDPOFQHPODJMYLKNAZCJFGITCKKBAJVCEANSRDMCOGSSXTJMJAYHIPQ': 'found_tokens',
    'LWIYSIZORVTMEMDGTLKJXBQXBEKABFBHWWLKPFBPHVMVCZCRSLYWHIINDWYTQNAHJJZNGNXVCQJEGHOLISUHB': 'found_user_ids',
    'ZHEEIJTWRYZKIFRNGGYSZWBHWBWKGDQRITLOHPVOAPQQMXTCDJYSXJYPPRLYXGXPYRCGOMKYVNBOP': 'token_sources',

    # Global değişkenler (collect_browser_data içindeki)
    'HHAYCFTKTMNFDVFHGXTGEIGCUNZWTTIWVQLKURZGORNLTITPRCBWKGVUSXWHDSZJTKEOHLCWOFZ': 'extensions_count',
    'LLAKXZWDVUXEWYVALNTXWRTZTRYQWBHHNZGIXYVYEZWYYBXHPFYODVMEOKHQDBAKRDITOFCPGLBBLCBGUEQLAMNQUFPCZ': 'passwords_count',
    'SXFIVDLQJNOHUWXUWMENBTUYORGBTDOTZIHMYQDOREJZHUQOZGFXUGKSSQANHEJQTUVLIVYDCMUFLSDPGONBGGYRB': 'cookies_count',
    'LCVQJACJQUOJIWIUKNUIMMOKCVGFNVRWVSJKVVNANTJZQWMWWSBNZPXRSIJKYTVRIDKHNLZVKRVBIHQXLTI': 'history_count',
    'IVMQVYBOVEIAPSPFMZLVSHMQNZLIKQOGPDTTZHHIGBXNSPQWAKCGNFACVADHGBDCQOZ': 'downloads_count',
    'PWRLAGIFURDSGOPBOEVKRATQAIOISNJZRJWVYIOAXIFHSNVBTGXI': 'cards_count',

    # Wallets/Apps dönüş değerleri
    'PCRDIMNXSQJXLBHTAPKKQOYISJNHMMKUBBISOHCQIDBNSXXXFUWJBBTVGZXQS': 'wallets_found',
    'KOVGSLXICZJOKYHGGFXDVRHDHXFUQFUMIYEXRPFPSXCALGCZERAUMOBINZZRTGLIISWWEQOUACONL': 'game_launchers_found',
    'RZHSBRKBHOMYDFQKKEWKYXNATSWWQOEBOQIDLKVROIAGTBPWNOOYFNQQSDJIRDYOOLKZAOOKHDP': 'apps_found',

    # Diğer yardımcılar
    'ACBPBPVUPIGWFAXXEPCPSXIHMHWNAUIYTPNVGNCGODTEKQUPZDMFJWOCSWCBJJX': 'is_windows',
    'ENQWFDIPTJKDAFHRRBXXHQFWFGSLDGDAITOSUSJNWBNKLRHUFAWDTTJHYQBRICTEFSFXDMXQLJHXHLXSXLYPNEFZANVGDOVJ': 'is_windows_result',
    'REIUILLJOMJTKGSUPOQMRBKURBJHLIPQMTTOJCRBJNLPUJYSCIOFGXYRXQHXBXWNFQKBFGLVEGBEQLGFD': 'original_subprocess_run',
    'OCDUHDOTFZLZLGWPFMEOZYXKZKRFOORLLEIUDUCLACYSATLMOCATAHB': 'create_no_window_flag',
    'BREMQVGVDFFPSONHCVQAVJGTGCBMFHZXTCRUKPMLIUCYTJTRTKVBQCQDQDNTMQQSVBWHSMAXESME': 'original_os_system',

    # Diğer anlamsız değişkenler (Discord işlemleri)
    'LJXUQFDFETHQLAFXVUCAYDQLTWNFALBNZVVOAORNJCFOONJFMRVWIEARPXDEJOYAHOLJHQDBFVPRHTFQYRRVTTVWKNUQGJKSNV': 'discord_output_text',
    'HHNPOKCGSWIXDFDTFZUMWZUQELWCDSRIDNPLBCBFRYJHKBDOXFNEQLBE': 'discord_accounts_count',
    'UUDZRVJTBEZEHOVBAEMHIEYALHMJEBNQIAZQBSVTUBSMTRTWTXNB': 'discord_username_tag',
    'CAGDNLMFMMXZAUCERHAYYRNHNESWCIDLWLDGSUOYJKYIHSWCOXRLLLHEFCGMXLKHNDCAWANJBJBCHLUEBRKY': 'discord_global_name',
    'JZXWULYMUOFNUWCXDZEROZYAAIOGRPLJEITKHGTUXKGIDHQIBQAUKGRURNVQLUFFIRIKYVKDABTNABCYUYUEDVGKGZPO': 'discord_user_id',
    'TSOWCZILKGCDZVSBKECCZQXOIUEUNFAYOPDMXYWLIQXEHASYFUGCQEQUENUUUHUOJAJZXBHTTYVRFRPUUZRXI': 'discord_email',
    'DIIFXPKBOURSLYVFYVSXQXIGRRUUAQTAQUAFUGHAJQANCTKNLKLESHNWGSNTXRKXCKIKGFLLBZOHXDFNGEC': 'discord_verified',
    'KNGSXNLIITYLJKEAEPCLEBPWQJPTCQXHCEKUUJORJWGVVZPEWZB': 'discord_phone',
    'FEUETYUTVGEBJTLFHNREVYBBMUQLVGJOBLMIYZTJNFKUAZOWTDNTVJDHYNYK': 'discord_locale',
    'WXDTNZKCSDIBMJHQHHMRXWGXKDYLNAIHCUHKKOZIVVKKAUETVBVOBHIRHONSNQTRCBZPQMVIV': 'discord_mfa_enabled',
    'GULTDMBULDZVTICFNSBLLIDKICKUUNOYLQIZUCBWUOSZFJWHWEEHVLH': 'discord_nitro_status',
    'XGBXIXURFLCCZYOHKSCDYZZESIOZWITNUWYCDCAXNXOBGBFRJJERIRQPUFYQYJUFKXFBFEHDDMXEKQPKRRDSADQHX': 'discord_gifts',
    'HIXKKCGXGKOSUDGTBHYDKBROGQXOTHYJIBFFNMIUXLBRFTWQYCJXORWHFCXWBPZVIUNKCSQUDMTQKBY': 'discord_gift_list',
    'WVDRAOLJRRBCKPRFJLTAJFDUWYBEZVZEZGGWUVVGDFLUPDMVLIMMHYRFFFOPTMUDEUYXCNEHSMDVFWRGYWRJPEAVIKFPVA': 'discord_avatar_url',
    'OAMUGKXOCWESXXMQSRKQMPKRNERADCBIHTBQAVSQCZUFBJCEBLUNVJHOJGCLBBASQBBVHMIUAFRMUCIKL': 'discord_payment_methods',
    'JWUWHSHGTXLDBIYGDMPMQATZKWUQMOXHOWSUMGIODIAWNWQVSDTEKOR': 'discord_billing_info',
    'PTKGEPYCBWOPYWRIYRRSKZSZIAGLMBCNQSYOFMPGQXAXTWVUHWQKVAOLYVPPGITWCUMHFTEJZF': 'discord_gift_code',
    'VMRZQWQUHPGMLBAPMGXLYGCCLMAKNRRJMHNUHUSSPQEACOBIYRWOSBGNKYEXQQMHQPWUSPNCAMYCNLPAYFW': 'discord_gift_formatted',
    'YFBVBPJSORMJUZACSIRINMUGZNSMUMCRHCKIWNOAHCKKEHQQOMIUZKPGHBVULNMWWQMDGQICXCKHENRECMAYT': 'generic_name',
    'QKLIOIUETRURCKSFLYMCQXIXRUXAETOBKPBUSPFMEIICOMSHKLYUMATZSKJGFZHMGZYEILQRIEFSGHQX': 'generic_path',
    'MMGQWIFPHTMWLYDVEOAMPELWOSVHLFFRBYALYJPVZDBTMDLUDLLZXWEOQSIWPVPMEEQRQFSUZNYPEETWJHLSI': 'discord_app_paths',
    'PJSRXHCCXVWGGXMYXNSNGKKGTQPRHYULAFFNYQUHIXPRANVNZBIJPASHLJGWAXJYWZMHTEHEDOKFZ': 'discord_process_name',
    'RICSSMJRBXQHTIBKZCXPIQFHQFHOKVPBPWMVQISPEZLUEEDSGPCIXREWRBXRJRGWLCMKBKENYOIKGXMCIAGGEDFLF': 'discord_file_path',
    'CJBUTPGARQYNNYJDOPNWJPCWBOYMGIGSMYGKQJPSAPZJVPVXATQLYBNVGHSBLGXYDBXWNNPQOANGJEL': 'discord_token_found',
    'DFIVIQIGTQWSTQBMRYXHMYXEPTDYELXATSCLFFUZAFNGMABPIOPYEHMNWQUL': 'discord_user_id_from_token',

    # Browser data içindeki yardımcı değişkenler
    'FPBHWVFZWRVBGUNCCZZINAGQUOZZWUADXPWIQQMYACSBNPHFDPEPSWJIOPLIP': 'browser_data_types',
    'YYLNLJUPLVFKFTANDVVWHOEZPOCPISKZNPIBIQKEDNEDCGDYZUAILHENGRRJRLCHPOHKSIRSMKEMJRCULDHJBWI': 'processed_browsers',
    'ZCEGHMEYAIQDORJKBBFIWUFFDYCHUSHXSUQEUIZIXVLXHZNIMYQWSGNUHUBDQDSQPQLOQKMFMDRFOZYRSVKWJDFPFJBDDBCOAQH': 'passwords_output',
    'FSCJVXDXZMYPVYSYGFVRIABXESNAOESDDOPTNJQPBKPXAKIUWFJKCPWGCBEQOTVVGPCRBMZZVXDVZOZTUZX': 'cookies_output',
    'JRMLVRVJTGRCYKELWFRPSGLKSOQZZESQUZGMSAULJKULHQEBGESOGLKROAAIAJVRDBI': 'history_output',
    'DXWBKMSEJOXQBNNZFNJQMNAEJKXKEABOJPXWRHSEEDRLICFAFTABMLRPYVVILMUJKVCBUKACIVEMDNTLAI': 'downloads_output',
    'BFBYODEVARFWMLNPKNVKVKYOZGLDCLGOHKGOVOJLZAKLMSMHEDDEVEYSBOLWZIFIOKTZJUJEWPDMMUBAX': 'cards_output',
    'MWPVAYQLSAQSPYOYSJAXJVMKITNYJLFEKPTESKCWGZPZAPDIRTPGAGZRJNMZWICEUEJFNVOMMEFQJAA': 'encrypted_key_data',
    'XLXNYVWYMNCXTKVLWISLALRLFFTLUMZYYTLGXUBZFGIEEMWYCC': 'aes_key',
    'XVYMKOZXGJBGGHOEATSQHAQCYNNXVKSWRQXOUMIOJMAHDFFYEBQFLPCOHAPPECZRTVJKCAAXBOEVGYLCIGJKMNSMBRQBNDZHNK': 'aes_iv',
    'BNNGBGQXSOZVZAWWAZJBKZKHHWYSNEHLANLROYUSIFDQCKTRTNGZCCYPMFUFNYBTVVJFGTZELJNYRQAEUHHMSTGUE': 'aes_ciphertext',
    'JXPUOVBVOMECQVFOFPAOXJCEJLOJNKJCGLMXRUCVBYOZBEUTEHEFPPJFEPYEZ': 'aes_tag',
    'MFQIPWRTRJXLUSIUKQXLEEUWNHHOEZAMTPNHLYJCHCMSJQBQEPUJPTIVLZWZTGSM': 'cipher_obj',
    'UYHLKXCVVGYLRNDWKOFXKFBABKBZPUTWVNTTVLZTCXTMWOCXCHHODABOSAZJFDMMNLNDZPAZPMRRHLRQZJ': 'decryptor_obj',
    'KSQBVXQAHQNYGLDGLFJYSWOOWNRUTMZDILUZTIGWGMADYMNFBXJTEKUNFUZASUSKNCLTAOPNSSLGMSMKXJBXXBYYMMOFOAYNKH': 'decrypted_data',
    'KDVUMGDGKARHRVDRHHHQEERKAYEVGPJDTIZCCKDRIAIHDJPCRGDCCHCLTJ': 'unpadder',
    'RAVXZRMPOGXNQLPMPXQQZJRHUZQZMDXNNVHNWGMSJZJJMLSLKDIWRRSJVBODPNZWDQZRIBZJOFMLLYLHCJKGERZHPREVIWWV': 'decrypted_final',
    'RGMOOHBIUYEUALWBFRPBFJRECHQREJRYNHUBJGGGQWNDOAFXVDYXDKRHKWJSTDYOZNLAXHIKDBXUMIIBDPWRDYETTDSCQDXAOPV': 'decoded_data',

    # Screenshot / Camera
    'HWAPVXETVCTNTKCFMTBTAYJNLXOOGPPESLDVCVSUAYRZGQVOCFVGLGBSEDYPPLVPEKXOBQPMWMPOQVORNASQHTRDMMLXQH': 'screenshot_status',
    'JYIQNGIYHLCMVBJFFLGIPFAVKEKXFWOEHSIPOSHTVAIAGZNHAQKPIILHJAHZESL': 'camera_status',
    'XBLXCIGFNOEHBKMOGIKAHPCRLXGGQUESJXENTKDIBVUVBDDBYWVOANACRLJXL': 'screenshot_bytes',
    'ETVZBJWRHTWMABNXCQWFGEULGRQHERVEUVPPMNIVBRPGKOQAQKUIDXXFBCXHLNRNIPZLGOQNKL': 'screenshot_image',
    'C4ptur3': 'capture_screen',
    'MRVBEHIDGFZNSKONSXCFOVRMNGDKECWCQYQYOETOEGSAEIDQHN': 'injection_status',
    'NIGXZABXTUEALOKXWHFGVQAMKHSBWOUUAILQZVZBCHOGDQUWLGICSGOPLSDJFNSCMTC': 'interesting_files_status',
    'EBSPCWUOZZIJHXQMLHSJKURJGWMWBOPBCFQRYCPPNIOCDDBOQHMSKTMGBDZDPWTDOUFCKKNBRPYNXXROCI': 'system_info_status',
    'WXKJCDTRYOPGDFXHTMMBZSEPKVIYSKCZLHZKJXQGBEKYFYTGDKHCLVLDLVZCASFXUTYVCICFDJPUQPMOFYFH': 'roblox_accounts_count',
    'KKILLPGICWLMSUETZGYPADTYPJUQNTJLPFKFYOCJMWSXMBXDILHQRBLKKGETRF': 'roblox_output_text',
    'JODHOQBBOPJFLSCKECFOKYGWFWYDOMAJLTSJELPOPFVNCLIMLPR': 'roblox_found_cookies',
    'GJFUFHNIEJTBLYUGQJVYJFYWIWJMLNNAUYQQHDGMXQFRZFTSAVTSWBFLBFOZZMLOKMHXGEKTVZDPMBCWPYELKTKCN': 'browser_cookie_functions',

    # Roblox bilgileri
    'VODALOHHGRIXQUSXYFICSYZRFGBVMPKRBYLAHRIIOAVAARRNFZUAHVGUJQWGWTSFBBGEHIWZWKBWSWFZAKSMBTIR': 'roblox_user_id',
    'RGPUCBRXNHMBGTHJRAJAWQWIUUITRVJTQAGBECLTCWHKXUFCILJIQFVTBICEYQBJSYRJHBHWKIOIECTSOAAT': 'roblox_display_name',
    'RVBNBLOBDFITKLIQGJXFINMADNFAYZMUBKDUMTRUHPBQHMAJRCOHXGLGJNPJXTHGBGDYFAVEJDD': 'roblox_username',
    'PKDBOTKRYQFVFRYEJHZGPOLFYFBJGXWACJZMCJUMWOSZASTUEZCTARBHTGLU': 'roblox_robux',
    'DEWIZWVDVAUEAPRIISUAZEBYRPIWGWBJPCABMBBTZNIVNZLTVZHKSUFFQHBTDYJYNWWOQQXUSOUXWHXQ': 'roblox_premium',
    'GLEVRZMWMMZBFGUEPMRYGXFPIZWQLDNYKINHKDHNTNRNCKRJEJAQTENOSHHNVQXPBCIAEUL': 'roblox_avatar_url',
    'NMUPWPWLKYYYBAPMIBVIBORFYSAHQHRPUYHLIMDQPMKRNCQDSBMXRKKFFKPROXDMXBKKK': 'roblox_builders_club',
    'MNVKNVFMEMEVULPEADPEGENWSJBPIIQJUJHHGTDCQKPDSEMNLQV': 'roblox_api_response',
    'YXNRVLKQRANXQPTJNJTDLOGEUQWCSVZWXNXLEXTZBJMPHTVYHZXVGHFCAKNUHYVHXFBVUIMXRHPUXQFBPFWBCIIFHSCNULDQQQ': 'roblox_cookie_value',
    'JHTNBQXFVNKEAUUPNZQGSXDZNVWVGMKYHQJVKSITYKLTJLSYCVBZW': 'browser_name',
    'CUXNAVGKXOKAFVCUJBBKSMXTMACKQZSITYLAADKUABRMBKZPJCLPGJMIHEAOGQEYIFUTZIQXPRMEUNCMDSHSPNH': 'cookie_func',
    'OIAYRMQZMKXFTQCFITEFWWPJSITQLMNSMIZKMOADLBNOUCHHDVLMMLKMKCK': 'cookie_str',

    # Yükleme ve Embed
    'ZQUTJPWEKMLVYLYOPTHLZYDTSTGZVTXSPXMOOJOUPBJPGSKXETTAOZ': 'zip_buffer',
    'SDLEXMGQEYJRSBVNRXALEVMCHPFXDNJBIDFLJHHXUVZXRGODCQMMCHMWJXHYKOMHOTNZPXLXNOR': 'zip_file',
    'AMCVYEMHUBTZFSPLAQKLDCRDQTMULIJGVWMRDVIZPYCRWPWZDOVXFLZHVBPFCAMBKFACLAMLWUAKUDNPVXQ': 'gofile_server',
    'WYVCJWYOYCFPDJESBEXRWWCTGNYTXBYDAUITINYLSJUKRVQRACZZJGDGGDSRRJMIVBMLQDOUWYXNSNTYMWYMDQYNETBVUHP': 'gofile_download_link',
    'OPMNQMESETBQZAWVYKAKOPVRVOTGUGBMKLSHNYKJBVUAHYXVFAEV': 'response_json',
    'LCEIOZLSTZRQXJPXSEJZYRJIKRGOUVWJMVOKIYCWUNPTXRLJTOQILOIJLJOPFDRRGRFFMZZERZQABOBFVMGS': 'api_data',
    'BLXBZLIFXUSKUHLSUIQZGCJKPYNGPXUMONFSEAFTWTVDAHQECZYXIWKOYFCSBYKHHMCQOVLGEMJQBSGQALLNYYFMRCGMMKFGFCN': 'stolen_items_list',
    'FRFJYGZWQZJHWZULWPRADTMHUHEWYAWFXMEGRIIQLVRRURDSXRTGCAZEZNFKHBMPQNKLFX': 'stolen_items_summary',
    'MACRWWXHVMEYUHOISMKUVUFAZTTELVKGDRHYADVXIBZMLWSXTSZFWVDEUNFNOKFJGFOBPOZGUTHMLIUL': 'webhook_url',
    'GLQKGRKZZHGGEYQPVEWWJYWNNLVRDXVFLYADEYYRLVLYMEATXCXYFYQEJSG': 'start_embed',
    'AJIEBVRHHJSSXTCBDWJMAQKBYCZBPCCHGZAKWXDUYDDXCZCQQKGGQZDZADMK': 'send_embed_with_retry',
    'LRBCKUOBLVUTUUPUNTRTMMKPNOWDENBSEEOHMCZBZCGMUVLCDYZZDTXSBA': 'sync_webhook',
    'XOKXZKQAROLFMRVGLNBGCJLGVKFWHWJCKAQVYYDCVXHIZMYZFNIDMACEVGDOFZSTOFK': 'payload_data',

    # Diğer genel
    'BNNBGBGQXSOZVZAWWAZJBKZKHHWYSNEHLANLROYUSIFDQCKTRTNGZCCYPMFUFNYBTVVJFGTZELJNYRQAEUHHMSTGUE': 'aes_ciphertext_2',
    'RTPOFEGKTGJNRGFOVXUFLNEEXWFHNRNMYACJVTDSVDQEFQNQHRYJUILMGSTSSCWLGMSKMQKJAT': 'derived_key',
    'GMPTSLKJQIODKDMYGMQOCCPQHEISSJQNFSIPWFQOMAJMIWLDMGOGSTETJYTROZOEAINFTIEOVIRHUKKSSZUQTESHDRBRWUE': 'pbkdf2_key',
    'YTHTXUJURQHMMQHOAGRHFMKGXUDFWUCVBSVCZDYKELFBBDTWFVLCPSGVKEMELPJAGQFQIBMWFLEHNJWAZNGPB': 'derive_key_from_password',
    'NNKINBNUWAOMRCEPHLOZEHUASVDHCRWCGBZMNNISCARPPYHILEBWNPCZVCMLJJQYKHYCKNTYBQXTFGYINKGKHDUVRRVCQILIYQ': 'salt_bytes',
    'GRQCYLUWWRSFOBDFEEWGKWFSRWXJSRZWUWQPQDGFXLFXCMULJHKULUPWEKBIPFQUSXQHXSBQGTFGFNAEALZJYFZBJOQLLB': 'base64_data',
    'MBPQVKOKAIRIKHJHEEMGWZABHNGSTMQXAAAGUVNXQTOLFOKHBBNWRHITKDVAQIDZICZNMMGGYDCKYZCYRXSJU': 'input_bytes',
    'PWKWSAAACXQRWZMMGMBYCPLAIDIQZIXURLSMTYVSUDDYMVVAVXPMXGVJVSVQIXWKTVXAVMBRCVKAGLGIJAAHUHKOB': 'password_str',
    'ESSEETWLRPTTGFKWJUTJQEVSLJPWAKULNUWBZZOJUTXYVOORPUSEDPFFOAOIQVT': 'plaintext_result',
    'BPLQMGTFPZZTZIBIDEMIRFIYWLPYHBJJOFDIEFIFMHJPBADKVMZYZHEBB': 'memory_db',
    'HMJIBJTZZPDGSGOXPFDCDNGGWWESIBMLCYYXFYWMRKVTKKNAMYDHHIQCZXHKBLCLZGCBKYQQMBWPPJVPRYO': 'file_db',
    'IPAHOIAOEQSUEWNGQYUKHZPBZHJPTJAVNCCXHKEXEFCHGYOMQVEMI': 'db_cursor',
    'BIYPBSHCUEDSZQEUTUEHSNZYPOWMGMOQWDXQNFOTHNNLCOGYERTJFTKWNZZIFKDVLDCDBSRGSJTXDVYWGSUTSSBBEIZTYZRARNT': 'total_bytes',
    'EEPGUMXURIILVCPMOIWUXRBMERMZIDNMRFOBUPSOEDZYRXBHOUIGVAQZ': 'free_bytes',
    'JSBLZFUFJUWXNJHCDHYDABMUQSNKNMLTSXUNMOYPPOIWONYDFZBQQBXHNBQXJOBSNZHUQSTCMPGUSSPWPWGYYOITJNU': 'used_bytes',
    'ZGPYIXXIVXGKTLAKASFZJAAXMWYFSJGUZVLXETOYOUNSMXATLOOLYMIXVKM': 'volume_name',
    'QXJFGERVKKKVGWGEDVADIZIJVUOTDRPUFTUHDRLANBHBFBSONACRHSVJWIFUD': 'drive_info_text',
    'DPHARODOFORBNGDWSYUJFRHRDALZLFMHZDPHCREJXQTXSHCVEWJDCR': 'used_percent',
    'NEGXYLTKCQTGZGIQPJUBJGAYYXPVUOJZAEWNBBSBCSSZKXXKTQUHTKOJENPWIXQFOYNHIGQPNYAFQSLWHPFIEJOTKGSR': 'free_gb',
    'ZMAHCRYDKPNWYXZXNDGHFVRRBBDVNZNOIOPRUCBQZNFZEPDUIGOAQKLFTDQSJJAUCVNPBDJBJJ': 'total_gb',
    'HEGFAWRUSAMDDTSTNEXAVSVHIYPGCQTMOBMGBIEEQLVQTYAFSTUYZOZKWMLNTBUHRLGNTV': 'used_percent_str',
    'SSCWAEGAHWZTNIROERVVPGFOTHOTHYQFNYIADRZETADNZULTOBLSSMOSK': 'pc_type',
    'NVGVQXBZBDAUCWKZFTNVXCDLFHJQBNSKLYQXVRGWCFUVXWUZGIZR': 'screen_count',
    'FYDAKBNIYRMQQWLBAFCDOISNKVFTOENTAFPCBKPYEDRIEGRDEXLYRXJGLRPS': 'os_name',
    'VQNCPONOYTAPUIAUMVYPUQEFMBDRMOJTOQHSLMPENYZIBVQDYSONITD': 'os_version',
    'RRHVMDJCBYOKGPVQSRYYFVLPGLGYVZDRPBRJJHJIYBWHPTBOQGIRTFTJYYIIHEOGSVUDGLOWIEJMPTALFQB': 'cpu_name',
    'AMDKOOSWECRKSAIICTQZYSGQUBSMLAIBIIGERVQVAWLJGTWMJJZUVAHOWORLLWDI': 'cpu_cores',
    'WIIWQZIDLKZMTBUYVZMLKFHJETTRUBTCJULTZNLQHIHYCJZZQZWYAWCURMYKQTQHGDPBIPCJCVTSGLBDHZQAB': 'gpu_name',
    'NPLGLFLYWFMHOKDDNDEQASGQFPJDRGGYQYRDVDJXGGLTTOLNZQTVDXCTLNSGDHAOJKRLLQA': 'ram_size',
    'HEWLKOCVZDMMOUPLHVZHHIIYMGEZNXHOYUPJGMFQQFJHCQENPACLLMYJHGKRNZAXLXERLXYOCQEOESSY': 'mac_address',
    'GTTGVDBNABZFPMBRGTYMJQKGBGBNOTXZGJJPHHLWGQXULMLKOPRTAIDZYLWYFDYOCCVJYFSWZBNSMRFUZCNPGAIJHUBZMELU': 'machine_guid',
    'GDQBZRVPHAUHJAGKFKMCIHAZKUGWLQXBIOHZFLSDZCKWHEZTDZJA': 'machine_id',
    'SGICHWAFWTCQCYCQUBRTBHMCDNLEJSRWFGWKMJLVURNVBICSLYXRQZEIJHKCYOCBRLAEFVKLOWFVLOJGRCFFIXFUVHQLKHT': 'hw_profile_guid',
    'TXDYNJAEKNNTQPCHZAIRLFZHKWYEYONHCKCWGJRQWVDGSMZXSEAVJZUUWZJPTSLNYHOKNRZWURJJNQFFGTKAEMGSBFPYKGONVLYA': 'nvidia_system_id',
    'PZRFFCJEPEIRXWXQVXDIJEIOGUOAZLINAHZKOZUIRAKGARCXMXPNYAKNKZ': 'guid_serial',
    'SKDHWYSNRZRBEGZDOTTPIKWSSISNTAFOOVQKPALSRVJLYMFPEAVJKFDMUXQFZOEIDNCARMGSAMQSFJRPCUMBJIDEYZTNREXLPQE': 'uuid_serial',
    'GFPULFXBWXQNZACZWAHTWRGFGLXBBPNCSVIPFUDXAVIAVLKCRJBZCDAVKOAOWZAMLVMA': 'motherboard_serial',
    'YMVUZLELYJMDNRPNVCJSVKDLVYLZWDQYQVKQUCGWBDPYCBCNUCRAPZPQXASEWHJLGXKH': 'motherboard_product',
    'HKGVRDNFNHJQCXYBYUUXJYKVGVIMQNFIXIJDIOHSPVPFQGPKEZPCTDXIVJJJDINZXNYEIBIFCRFLRBWLFXXRCIAKOCJGJCE': 'motherboard_manufacturer',
    'ADVOYUPPUHQPMOZAXSBIUYBNUEPFIPTXVMXPQPDEEMEZXTPBIHAKTAJE': 'processor_serial',
    'LEVLTJJXHSVYNXVSIJGZZZPWLEQRSFDOQESRCOKQRALQAPXVKZBAWK': 'bios_serial',
    'TYJRMIIFZPUTZSIEACHEKYDXKHMOORDVWDSKTOLAIVVQOWNVXTPYRFKCFVWGFOEVXX': 'bios_release_date',
    'IPWRJYRZYUFTDMLAINQHSYYDCKWESKJSCZUDDSHVDPCVHDWABHJENSMBIWYNYXLSHUQFLVZCN': 'bios_version',
    'MAKIVGSGZAXDSTUKGWYYXBWLOYYWELQQBKUWCHMQQFCUZFAHLFSSAXIKEWCV': 'system_bios_version',
    'WXUJTGZGATVRJIVORJSXCRMFSLWSXGGTQTPLARALHSDHZUDJLWSYFWLGSFPJGSNRRITWQBTZK': 'system_version',
    'MJZVESUSFTLOFWMREJPISXSLTQPCGRWJZMOOCUAPXRQDEFXGLAHITHNJAJXWXXDMEUSWRVLVFAUHOGWYDPZOUB': 'system_family',
    'SRHJDQCXUIRDIVIGUOJYACMVGMLQHSKVSEUCIWMHPWDETQTEWLOTVOWZMALUIBRXOSEYPJUGTUXWGTSKTGIKNTJLXFXXADWUNO': 'system_manufacturer',
    'YZVTHGSPSNDWCPQSIMHVJHZVEMFMCGYOKLFPJPAOZICEAFPSVCDFJGTXYZQJFDLFEDYZ': 'system_product',
    'NWYOTBTTFTJHFLTQHOJHHNQLSGZLCGSVEQNAIXOKKITXQDZEACUCYEM': 'system_sku',
    'SVZTNKIHIKXZOTAKQMWRWNJJNWGAOBDTDJTFDLVUJRWOYIHSCDRYTUQISITCPXUFUHNETQA': 'oem_strings',
    'UEEFTBFXSVRWDRBBCWSJQZLCIAXCOFWPNSUTEASAQYQRMEQQWXZXFLZ': 'asset_tag',
    'PASOSRSGXWEWEYUMQDZLCUWJAMIHZAEAWNUPRSHVXHXCIEVAUKOVWAUTFLDWRVZOLWDNEQGOZZROWNTDATAMUWCPTDQWLARZ': 'drive_letter',
    'JDGLUREWMLQMLKGDHAXIAEFUAEULPYCUWEVIQHWHKHCNYMEILVJ': 'drives_list',
    'LQTFLFITJVGAKCPKZWEEFWLYDDFLYTZWZVBTUHXBLIGSOFFGCXJCKFQVJIALIROJMGHABJC': 'drive_bitmask',

    # Browser data path list
    'SDLESDHMDEDHALPXQPFKAUHPUPVIESRNBJLWJRSFSTZZLRUBRUDG': 'browser_paths',
    'BWZQDUVMYTOEHLIHXBMTJWHEMPTRMEMLCXIDULZITZFQZTDPPKZBFNDKFHGW': 'browser_profiles',
    'ZWCULLMREOTSISUAGIVRFRYMATLQDAQKDFTBVEQGMTIFVWSSTZHBJHQIMFNTTMMAHFVSGPTMFPIJERYFYNTJAVCLFVDHY': 'extension_mapping',

    # Wallets paths
    'WalletWasabi': 'wallet_wasabi_list',

    # Yükleme ve hata mesajları
    'D3f_R4n50mw4r3Run': 'run_stealer_main',
    'v4r_gofile_attempt': 'gofile_attempt',
    'v4r_t0k3n_d15c0rd': 'token_loop',
    'v4r_br0ws3r': 'browser_func_loop',
    'v4r_c00ki3': 'cookie_loop',
    'v4r_extension_name': 'ext_name',
    'v4r_extension_folder': 'ext_folder',
    'v4r_extention': 'ext_id',
    'v4r_item': 'item',
    'v4r_root': 'root_dir',
    'v4r_files': 'file_list',
    'v4r_file': 'file_name',
    'v4r_drive': 'drive_info',
    'v4r_letter': 'drive_letter_loop',
    'v4r_profile': 'profile_name',
    'v4r_proc': 'process_obj',
    'v4r_proc_name': 'process_name',
    'v4r_method': 'payment_method',
    'v4r_type': 'category_type',
    'v4r_software_name': 'software_name',
    'v4r_row': 'row_data',
    'v4r_line': 'line_data',
    'v4r_file_name': 'file_name_loop',
    'v4r__file': 'sqlite_file',
    'v4r_f': 'file_handle',
    'v4r_value': 'reg_value',
    'v4r_reg_type': 'reg_type',
    'v4r_func': 'func_ref',
}

# ---------- 2. GEREKSİZ GLOBAL BİLDİRİMLERİNİ KALDIR ----------
def remove_global_lines(code):
    lines = code.split('\n')
    new_lines = []
    for line in lines:
        stripped = line.strip()
        if stripped.startswith('global ') and all(c.isalpha() or c == '_' for c in stripped.replace('global ', '').replace(',', '').strip().split()):
            # Sadece rastgele büyük harfli global'leri kaldır (anlamlı olmayanları)
            parts = stripped.replace('global ', '').replace(',', '').strip().split()
            is_junk = True
            for p in parts:
                if p in ['extensions_count', 'passwords_count', 'cookies_count', 'history_count', 'downloads_count', 'cards_count']:
                    is_junk = False
                    break
            if is_junk:
                continue  # Satırı atla
        new_lines.append(line)
    return '\n'.join(new_lines)

# ---------- 3. İNDENTASYON DÜZELTME (Temel) ----------
def fix_indentation(code):
    lines = code.split('\n')
    new_lines = []
    indent_stack = [0]  # boşluk sayısı
    prev_line_indent = 0
    prev_line_stripped = ""

    for line in lines:
        if not line.strip():
            new_lines.append(line)
            continue

        current_indent = len(line) - len(line.lstrip())
        stripped = line.lstrip()

        # Eğer satır `except`, `else`, `elif`, `finally` ile başlıyorsa, bir önceki blok seviyesine çek
        if stripped.startswith(('except ', 'except:', 'else:', 'elif ', 'finally:')):
            # Bir önceki satırın indentini bul (try/if/for)
            # Basitçe: eğer bir üst seviyede try varsa, onu bulmak için stack kullan.
            # Kolaylık olsun diye 4 boşluk geri al
            if len(indent_stack) > 1:
                target_indent = indent_stack[-2]
            else:
                target_indent = max(0, current_indent - 4)
            # Satırı yeniden oluştur
            line = ' ' * target_indent + stripped
            new_lines.append(line)
            # Stack'i güncelle
            if stripped.endswith(':'):
                indent_stack.append(target_indent + 4)
            continue

        # Normal blok başlangıçları (if, for, while, def, class, try, with)
        if stripped.endswith(':') and not stripped.startswith(('except ', 'except:', 'else:', 'elif ', 'finally:')):
            # Yeni blok seviyesi ekle
            indent_stack.append(current_indent + 4)
            new_lines.append(line)
            prev_line_indent = current_indent
            prev_line_stripped = stripped
            continue

        # Eğer satır 'return', 'pass', 'break', 'continue' ile başlıyorsa ve mevcut indent bir önceki satırdan büyükse,
        # ama önceki satır blok başlangıcı değilse (hatalı olabilir), düzeltmeyi dene.
        if stripped.startswith(('return ', 'return', 'pass', 'break', 'continue')):
            if len(indent_stack) > 1 and current_indent > indent_stack[-2]:
                # Eğer önceki satır ':' ile bitiyorsa ve bu satır o blokta olmalı, ama indent çok fazla
                # Basitçe bir önceki blok seviyesine çek
                line = ' ' * (indent_stack[-2]) + stripped
                new_lines.append(line)
                continue

        new_lines.append(line)

    return '\n'.join(new_lines)

# ---------- 4. ÖZEL SYNTAX HATALARINI DÜZELT ----------
def fix_known_errors(code):
    # f-string içinde çift tırnak çakışması (replace(' ', '_') )
    # Orijinal: f'BLX_{EBSOKFT...replace(' ', '_')}.zip'
    # Düzelt: f'BLX_{EBSOKFT...replace(" ", "_")}.zip'
    code = re.sub(r"replace\(' ', '_'\)", 'replace(" ", "_")', code)
    # Ayrıca başka yerde tek tırnak içinde çift tırnak vs.
    return code

# ---------- 5. YORUM SATIRLARINI TEMİZLE ----------
def clean_comments(code):
    code = re.sub(r'# irreducible cflow, using cdg fallback', '# fixed flow', code)
    return code

# ---------- 6. BOŞ FONKSİYONLARI KALDIR (opsiyonel) ----------
def remove_empty_functions(code):
    # Sadece `def empty_thread_X():` şeklindeki boş fonksiyonları kaldır.
    pattern = r'def empty_thread_\d+\(\):\s+return\s*\n'
    code = re.sub(pattern, '', code)
    return code

# ---------- 7. ANA DÖNÜŞÜM FONKSİYONU ----------
def full_deobfuscate(input_file, output_file):
    if not os.path.exists(input_file):
        print(f"Hata: {input_file} bulunamadı.")
        return

    with open(input_file, 'r', encoding='utf-8', errors='ignore') as f:
        code = f.read()

    print("[1/6] Özel sözdizimi hataları düzeltiliyor...")
    code = fix_known_errors(code)

    print("[2/6] Gereksiz global bildirimleri kaldırılıyor...")
    code = remove_global_lines(code)

    print("[3/6] Anlamsız boş fonksiyonlar temizleniyor...")
    code = remove_empty_functions(code)

    print("[4/6] İsimler anlamlı hale getiriliyor (Regex ile)...")
    # Uzun isimleri değiştir (en uzundan başlayarak)
    sorted_map = sorted(REPLACE_MAP.items(), key=lambda x: len(x[0]), reverse=True)
    for old, new in sorted_map:
        # Tam kelime eşleşmesi için \b kullan, ama nokta ve alt çizgi ile çevrili olabilir.
        # Python identifier'larında \b yeterlidir.
        code = re.sub(r'(?<![A-Za-z0-9_])' + re.escape(old) + r'(?![A-Za-z0-9_])', new, code)

    print("[5/6] Yorum ve etiketler temizleniyor...")
    code = clean_comments(code)

    print("[6/6] İndentasyon düzeltiliyor (deneme)...")
    code = fix_indentation(code)

    # Ekstra: Başlangıçtaki gereksiz global satırlarını tekrar temizle (kalanları)
    code = remove_global_lines(code)

    # Son kontrol: 'None' döndüren boş fonksiyonları temizle (bazıları kaldıysa)
    # Ama tamamen kaldırmak yerine yorum satırı yapalım, çünkü çağrılıyor olabilir.
    # Şimdilik bırakıyorum.

    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(code)

    print(f"\n✅ Deobfuscation tamamlandı! Çıktı dosyası: {output_file}")
    print("⚠️ UYARI: Oluşan dosya hala zararlı kod içerir. KESİNLİKLE ÇALIŞTIRMAYIN!")
    print("   İndentasyon hataları tamamen düzeltilemeyebilir. Elle gözden geçirin.")

if __name__ == '__main__':
    if len(sys.argv) > 1:
        input_file = sys.argv[1]
        output_file = sys.argv[2] if len(sys.argv) > 2 else input_file.replace('.py', '_deobf.py')
    else:
        input_file = 'malware.py'
        output_file = 'malware_deobfuscated_final.py'
    full_deobfuscate(input_file, output_file)